### PR TITLE
Contract Finalization & Tests

### PR DESCRIPTION
**Pull request by masonchain**
Not ready for merging yet but not a fan of issue discussions tbh.

### CODE REVIEW

**Comment by masonchain** [comment]
The nested initializer within BadgerScout was throwing an error any way it happened. Removing this internal _initialize and handling everything within the external initialize has no issues.

@nftchance Let me know if you think this is an okay solution.

Continuing on with new tests now

**Comment by nftchance** [comment]
Sounds good -- there's a few small issues I need to loop back on:

New subscription/license implementation
Ability to change name/symbol of badge
Add all token type receivables and withdrawables

If it's not one of those 3, good to make any needed changes

**Comment by nftchance** [comment]
Could also do any of those 3, but rn any changes that have to be made are good to be made as long as the model doesn't change

**Comment by masonchain** [comment]
Sounds good, I'll document when I hit them

**Comment by nftchance** [comment]
I forgot the last change that needs to be made is making every field batch able.

But that's going to fuck people if they don't do multiple ids so we will need a fullBatch and batch (the existing one)

**Comment by nftchance** [comment]
Above, is all the contract thoughts I'm currently holding. Can change or fix any of them

**Pull request closed without merging**
